#! /usr/bin/env python
import rospy
import roslib.message
import functools
import sys
import std_msgs.msg
from sam_helpers.reader import SAMReader

def callback(msg, name):
    rospy.loginfo("[%s]: %s" % (name, msg))

if __name__ == '__main__':
    rospy.init_node('slot_echo', anonymous=True)
    argv = rospy.myargv(argv=sys.argv)
    if len(argv) > 1:
        slot_name = argv[1]
    
    reader = SAMReader(slot_name,
                       functools.partial(callback,name=slot_name))
    
    rospy.spin()