#! /usr/bin/env python
import sys
import rospy
from manager import Manager
from repository import Repository

if __name__ == '__main__':
    rospy.init_node('sam_node')
    f_yaml = None
    argv = rospy.myargv(argv=sys.argv)
    if len(argv) > 1:
        f_yaml = argv[1]
    repo = Repository(f_yaml)
    manager = Manager(repo)
    
    rospy.spin()