#! /usr/bin/env python
import rospy
from multimaster_bridge import MultimasterBridge

if __name__ == '__main__':
    rospy.init_node('sam_multimaster')

    mb = MultimasterBridge()

    rospy.spin()
